/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerdictShareIdRouteImport } from './routes/verdict.$shareId'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerdictShareIdRoute = VerdictShareIdRouteImport.update({
  id: '/verdict/$shareId',
  path: '/verdict/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/stats': typeof StatsRoute
  '/verdict/$shareId': typeof VerdictShareIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/stats': typeof StatsRoute
  '/verdict/$shareId': typeof VerdictShareIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/stats': typeof StatsRoute
  '/verdict/$shareId': typeof VerdictShareIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/stats'
    | '/verdict/$shareId'
    | '/api/auth/callback'
    | '/api/auth/logout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/stats'
    | '/verdict/$shareId'
    | '/api/auth/callback'
    | '/api/auth/logout'
  id:
    | '__root__'
    | '/'
    | '/logout'
    | '/stats'
    | '/verdict/$shareId'
    | '/api/auth/callback'
    | '/api/auth/logout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogoutRoute: typeof LogoutRoute
  StatsRoute: typeof StatsRoute
  VerdictShareIdRoute: typeof VerdictShareIdRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verdict/$shareId': {
      id: '/verdict/$shareId'
      path: '/verdict/$shareId'
      fullPath: '/verdict/$shareId'
      preLoaderRoute: typeof VerdictShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogoutRoute: LogoutRoute,
  StatsRoute: StatsRoute,
  VerdictShareIdRoute: VerdictShareIdRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
